### ISSUE TITLE
CORS policy error: No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by azankl** [ccmbioinfo/NeuralCR#20]
Hi Aryan,

I am working on a Chrome extension that makes use of the NeuralCR API, but I am getting a CORS policy error:

Access to XMLHttpRequest at 'https://ncr.ccm.sickkids.ca/curr/match/?text=optic+disc+swelling+m' from origin 'chrome-extension://dkknhicdbaklmnblmmliepfeekmojahf' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Could you please add the missing header on your server?
Thanks
Andreas

**Comment by a-arbabi** [comment]
Hi Andreas,

Thanks for your interest in NCR. The web app provided at ncr.ccm.sickkids.ca is for demonstration purposes. I think the best way to use NCR for your project would be to deploy it from the source code available here (which includes the source code for the web app too).
